/* ============================================================
   CONFIG — Recognition Points (v6 — categorías de premios GN Argentina)
   El único archivo que necesitás editar.
   ============================================================ */

window.APP_CONFIG = {

  STORAGE_MODE: 'mailto',

  MAIL: {
    ADMIN_EMAIL: 'juan.i.da.torre@accenture.com',
    SUBJECT_PREFIX: 'RP-FY26-VOTE',
    FIELD_SEP: '|',
    NOMINEE_SEP: ';',
    MAX_JUSTIFICATION_CHARS: 500
  },

  /* ------------------------------------------------------------
     CATEGORÍAS DE PREMIOS — GN Argentina Recognition Awards
     type: 'individual' (1 nominado) | 'team' (hasta maxNominees)
     eligibleLevels: [] = todos; o array con niveles permitidos
     ------------------------------------------------------------ */
  CATEGORIES: [
    {
      id: 'inspiring-leader',
      name: 'Inspiring Leader',
      description: 'Para ejecutivos que coachearon, inspiraron y motivaron a otros en su desarrollo personal y profesional.',
      type: 'individual',
      maxNominees: 1,
      eligibleLevels: ['M. Director', 'Manager', 'Senior Manager', 'Associate Director'],
      badge: 'Premio Individual'
    },
    {
      id: 'breaking-new',
      name: 'Breaking New',
      description: 'Para quienes dieron un paso más al crear o implementar una solución innovadora o renovar procesos.',
      type: 'individual',
      maxNominees: 1,
      eligibleLevels: [],
      badge: 'Premio Individual'
    },
    {
      id: 'engagement-champion',
      name: 'Engagement Champion',
      description: 'Para quienes personifican la cultura de Accenture y motivan al equipo con actividades y acciones concretas.',
      type: 'individual',
      maxNominees: 1,
      eligibleLevels: [],
      badge: 'Premio Individual'
    },
    {
      id: 'dream-team',
      name: 'Dream Team',
      description: 'Para equipos que demostraron una performance superior o resultados excepcionales a través de su compromiso conjunto.',
      type: 'team',
      maxNominees: 10,
      eligibleLevels: [],
      badge: 'Premio de Equipo'
    },
    {
      id: 'big-hearts',
      name: 'Big Hearts',
      description: 'Para equipos que fueron más allá dedicando su tiempo y esfuerzo a actividades de voluntariado.',
      type: 'team',
      maxNominees: 10,
      eligibleLevels: [],
      badge: 'Premio de Equipo'
    }
  ],

  /* ------------------------------------------------------------
     EQUIPO COMPLETO — 135 miembros (Book1.xlsx · 2026-07-14)
     Cada entrada: { id, name, level }
     ------------------------------------------------------------ */
  TEAM: [
    { id: 'micaela.v.alvarez', name: 'Micaela Valeria Álvarez', level: 'M. Director' },
    { id: 'lucia.miguel', name: 'Lucia Miguel', level: 'Associate Director' },
    { id: 'mario.a.ambrosone', name: 'Mario Ambrosone', level: 'Senior Manager' },
    { id: 'guillermina.zarich', name: 'Guillermina Zarich', level: 'Manager' },
    { id: 'evelyn.mazzini', name: 'Evelyn Mazzini', level: 'Manager' },
    { id: 'susana.c.gonzalez', name: 'Susana González', level: 'Senior Manager' },
    { id: 'g.truszkowski', name: 'Guillermo Truszkowski', level: 'Senior Manager' },
    { id: 'natalia.santelli', name: 'Natalia Andrea Santelli', level: 'Senior Manager' },
    { id: 'ignacio.hierrezuelo', name: 'Ignacio Hierrezuelo', level: 'Senior Manager' },
    { id: 'flavio.carrozza', name: 'Flavio Carrozza', level: 'Associate Manager' },
    { id: 'maria.florencia.val', name: 'María Florencia Val', level: 'Senior Manager' },
    { id: 'alejandra.cristofano', name: 'Alejandra Cristofano', level: 'Consultant' },
    { id: 'cintia.ledesma', name: 'Cintia Ledesma', level: 'Manager' },
    { id: 'florencia.ghirelli', name: 'Florencia Ghirelli', level: 'Manager' },
    { id: 'lucia.minones', name: 'Lucía Miñones', level: 'Consultant' },
    { id: 'romina.santander', name: 'Romina Santander', level: 'Senior Manager' },
    { id: 'lucas.fresta', name: 'Lucas Fresta', level: 'Associate Manager' },
    { id: 'maria.s.urrutia', name: 'María Soledad Urrutia', level: 'Senior Manager' },
    { id: 'silvia.reyna.rickert', name: 'Silvia Reyna Rickert', level: 'M. Director' },
    { id: 'flavia.voloschin', name: 'Flavia Voloschin', level: 'Manager' },
    { id: 'antonella.s.costanzo', name: 'Antonella Costanzo', level: 'Manager' },
    { id: 'cynthia.behrends', name: 'Cynthia Behrends', level: 'Manager' },
    { id: 'florencia.higa', name: 'Florencia Higa', level: 'Associate Manager' },
    { id: 'julian.merello', name: 'Julian Merello', level: 'Associate Manager' },
    { id: 'nicolas.goycoolea', name: 'Nicolas Goycoolea', level: 'Consultant' },
    { id: 'jonathan.blejman', name: 'Jonathan Blejman', level: 'Senior Manager' },
    { id: 'martina.bartolini', name: 'Martina Bartolini', level: 'Associate Manager' },
    { id: 'sebastian.vinao', name: 'Sebastian Vinao', level: 'Manager' },
    { id: 'facundo.toledo', name: 'Facundo Toledo', level: 'Associate Manager' },
    { id: 'antonela.rossi', name: 'Antonela Rossi Santana', level: 'Manager' },
    { id: 's.herrero', name: 'Sebastian Herrero', level: 'Manager' },
    { id: 'mauro.vera', name: 'Mauro Vera', level: 'Consultant' },
    { id: 'claudia.del.v.baez', name: 'Claudia del Valle Baez', level: 'Manager' },
    { id: 'a.x.babuin', name: 'Anabella Babuin', level: 'Associate Director' },
    { id: 'julian.chereque', name: 'Julián Ezequiel Chereque', level: 'Manager' },
    { id: 'agustina.a.diaz', name: 'Agustina Diaz', level: 'Consultant' },
    { id: 'i.sallaz.joannas', name: 'Indira Sallaz Joannas', level: 'Manager' },
    { id: 'ana.bringas', name: 'Ana Bringas', level: 'Associate Manager' },
    { id: 'diego.wawrynczak', name: 'Diego Wawrynczak', level: 'Associate Manager' },
    { id: 'nicolas.pepino', name: 'Nicolas Pepino', level: 'Manager' },
    { id: 'guillermina.zubieta', name: 'Guillermina Zubieta', level: 'Consultant' },
    { id: 'dafne.riera', name: 'Dafne Riera', level: 'Manager' },
    { id: 'lucila.tejerina', name: 'Lucila Tejerina', level: 'Consultant' },
    { id: 'julieta.sikora', name: 'Julieta Sikora', level: 'Senior Analyst' },
    { id: 'e.gonzalez.kees', name: 'Enrique Gonzalez Kees', level: 'Senior Analyst' },
    { id: 'rosario.medina', name: 'Rosario Medina', level: 'Consultant' },
    { id: 'santiago.a.ruiz', name: 'Santiago Ruiz', level: 'Analyst' },
    { id: 'tomas.medrano', name: 'Tomas Medrano', level: 'Analyst' },
    { id: 'celina.davola', name: 'Celina Davola', level: 'Associate Manager' },
    { id: 'martin.grau', name: 'Martin Grau', level: 'Consultant' },
    { id: 'f.arias', name: 'Fernando Arias', level: 'Analyst' },
    { id: 'leonardo.barassi', name: 'Leonardo Barassi', level: 'Consultant' },
    { id: 'carolina.cabrera', name: 'Carolina Cabrera', level: 'Senior Analyst' },
    { id: 'nahuel.alberdi', name: 'Nahuel Alberdi', level: 'Manager' },
    { id: 'sofia.lazzarin', name: 'Sofia Lazzarin', level: 'Consultant' },
    { id: 'v.b.lopez', name: 'Valentina Lopez', level: 'Consultant' },
    { id: 'jorman.manrique', name: 'Jorman Manrique', level: 'Consultant' },
    { id: 'micaela.noya', name: 'Micaela Noya', level: 'Senior Analyst' },
    { id: 'c.a.gutierrez.ocampo', name: 'Cristina Gutierrez Ocampo', level: 'Associate Manager' },
    { id: 'roberta.palarino', name: 'Roberta Palarino', level: 'Associate Manager' },
    { id: 'tiago.prado', name: 'Tiago Prado', level: 'Consultant' },
    { id: 'carolina.bucich', name: 'Carolina Bucich', level: 'Analyst' },
    { id: 'ana.galsman', name: 'Ana Galsman', level: 'Analyst' },
    { id: 'ramiro.lopez', name: 'Ramiro Lopez', level: 'Analyst' },
    { id: 'juan.i.da.torre', name: 'Juan Ignacio da Torre', level: 'Analyst' },
    { id: 'juan.ogorodrik', name: 'Juan Ogorodrik', level: 'Senior Analyst' },
    { id: 'tomas.colomer', name: 'Tomas Colomer', level: 'Senior Analyst' },
    { id: 'dolores.ceverens', name: 'Dolores Ceverens', level: 'Associate Manager' },
    { id: 's.gonzalez.del.solar', name: 'Santiago Gonzalez del Solar', level: 'Analyst' },
    { id: 'nicolas.a.schneider', name: 'Nicolas Schneider', level: 'Analyst' },
    { id: 'debora.vanesa.di.dio', name: 'Debora Vanesa Di Dio', level: 'Senior Manager' },
    { id: 'delfina.sayans', name: 'Delfina Sayans', level: 'Analyst' },
    { id: 'alexia.esersky', name: 'Alexia Esersky', level: 'Associate' },
    { id: 'tomas.carzolio', name: 'Tomas Carzolio', level: 'Associate' },
    { id: 'juan.g.fernandez', name: 'Juan Fernandez', level: 'Analyst' },
    { id: 'santiago.longo', name: 'Santiago Longo', level: 'Analyst' },
    { id: 'f.m.martinez.thoss', name: 'Fernanda Martinez Thoss', level: 'Consultant' },
    { id: 'bernadette.v.estrin', name: 'Bernadette Estrin', level: 'Consultant' },
    { id: 'eliana.a.esquer', name: 'Eliana A. Esquer', level: 'Consultant' },
    { id: 'julieta.rapan', name: 'Julieta Rapan', level: 'Senior Analyst' },
    { id: 'lucila.sanchez', name: 'Lucila Sanchez Galceran', level: 'Analyst' },
    { id: 'francisco.j.diez', name: 'Francisco Diez', level: 'Senior Analyst' },
    { id: 'maximiliano.banegas', name: 'Maximiliano Banegas', level: 'Consultant' },
    { id: 'gabriel.fernadez', name: 'Gabriel Fernadez', level: 'Senior Analyst' },
    { id: 'mariano.r.caviglia', name: 'Mariano Caviglia', level: 'Senior Analyst' },
    { id: 'gaston.gallur', name: 'Gaston Gallur', level: 'Consultant' },
    { id: 'barby.levy', name: 'Barbara Sonia Levy', level: 'Manager' },
    { id: 'manuel.abasgoitia', name: 'Manuel Abasgoitia', level: 'Consultant' },
    { id: 'alejandro.bandi', name: 'Alejandro Bandi', level: 'Manager' },
    { id: 'gustavo.a.nunez', name: 'Gustavo Nuñez', level: 'Consultant' },
    { id: 'mariana.solari', name: 'Mariana Solari', level: 'Consultant' },
    { id: 'isidoro.centanni', name: 'Isidoro Centanni', level: 'Manager' },
    { id: 'javier.a.santiago', name: 'Javier Santiago', level: 'Consultant' },
    { id: 'fabian.f.yamazato', name: 'Fabian F. Yamazato', level: 'Senior Analyst' },
    { id: 'marcelo.s.roumie', name: 'Marcelo Roumie', level: 'Associate Manager' },
    { id: 'anahi.m.sanchez', name: 'Anahi Sanchez', level: 'Consultant' },
    { id: 'patricia.b.volpini', name: 'Patricia Volpini', level: 'Consultant' },
    { id: 'esteban.yona', name: 'Esteban Yona', level: 'Consultant' },
    { id: 'valeria.rubinstein', name: 'Valeria Rubinstein', level: 'Senior Manager' },
    { id: 'natalia.marchitelli', name: 'Natalia Marchitelli', level: 'Manager' },
    { id: 'jonathan.ballarini', name: 'Jonathan Ballarini', level: 'Senior Analyst' },
    { id: 's.a.aberastegui', name: 'Sabrina Aberastegui', level: 'Consultant' },
    { id: 'tobias.whelan', name: 'Tobias Whelan', level: 'Consultant' },
    { id: 'gaston.l.pugliese', name: 'Gaston Pugliese', level: 'Consultant' },
    { id: 'francisco.fregona', name: 'Francisco Fregona', level: 'Consultant' },
    { id: 'marcos.traversaro', name: 'Marcos Traversaro', level: 'Analyst' },
    { id: 'ian.rotmistrovsky', name: 'Ian Rotmistrovsky', level: 'Analyst' },
    { id: 'martin.blufstein', name: 'Martin Blufstein', level: 'Analyst' },
    { id: 'luca.besio', name: 'Luca Besio', level: 'Consultant' },
    { id: 'martin.n.bruno', name: 'Martin Nicolas Bruno', level: 'Senior Analyst' },
    { id: 'fernanda.reca', name: 'Fernanda Reca', level: 'Manager' },
    { id: 'lucas.i.filippelli', name: 'Lucas Filippelli', level: 'Analyst' },
    { id: 'francisco.c.lopez', name: 'Francisco Ariel Lopez', level: 'Associate' },
    { id: 'blas.maria.gallo', name: 'Blas Maria Gallo', level: 'Associate' },
    { id: 'miguel.a.inchausti', name: 'Miguel Inchausti', level: 'Associate' },
    { id: 's.blatter.torcello', name: 'Sofia Blatter Torcello', level: 'Associate' },
    { id: 'l.gonzalez.del.campo', name: 'Lucas Gonzalez Del Campo', level: 'Associate' },
    { id: 'marcos.h.delgui', name: 'Marcos Delgui', level: 'Associate' },
    { id: 'nina.peretti', name: 'Nina Peretti', level: 'Associate' },
    { id: 'sol.faga', name: 'Sol Faga', level: 'Associate' },
    { id: 'felicitas.mesa', name: 'Felicitas Mesa', level: 'Associate' },
    { id: 'lola.paulet', name: 'Lola Paulet', level: 'Associate' },
    { id: 'sofia.yanez.arauz', name: 'Sofía Yañez', level: 'Analyst' },
    { id: 'julia.galarce', name: 'Julia Galarce', level: 'Analyst' },
    { id: 'matias.c.muhamed', name: 'Matias Muhamed', level: 'Senior Manager' },
    { id: 'tomas.goncevatt', name: 'Tomas Goncevatt', level: 'Senior Analyst' },
    { id: 'f.b.diaz', name: 'Francisco Diaz', level: 'Analyst' },
    { id: 'lucas.fabricius', name: 'Lucas Fabricius', level: 'Analyst' },
    { id: 'mateo.fornari', name: 'Teo Fornari', level: 'Analyst' },
    { id: 'lara.b.fortunato', name: 'Lara Fortunato', level: 'Analyst' },
    { id: 'agustina.a.aguilera', name: 'Agustina Aguilera', level: 'Analyst' },
    { id: 'matias.n.blanco', name: 'Matias Nicolas Blanco', level: 'Analyst' },
    { id: 'm.salatino.rava', name: 'Martina Salatino Rava', level: 'Consultant' },
    { id: 'manuel.f.gonzalez', name: 'Manuel Gonzalez', level: 'Analyst' },
    { id: 'martina.juanche', name: 'Martina Juanche', level: 'Analyst' }
  ]
};
